version: "3"
services:
  api:
    restart: unless-stopped
    build: .
    environment:
      - POSTGRES_URL=${POSTGRES_URL:-postgres:5432/}
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
    expose:
      - 80
  postgres:
    restart: unless-stopped
    image: postgres
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - postgres
      - api
volumes:
  postgres-data:
